import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Jetblue 25 for 25 Route Optimizer',
  description: 'Generated by GZ',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <footer className='flex items-center justify-center w-full h-24 border-t text-emerald-700 font-semibold'>

        </footer>
      </body>
    </html>
  );
}
